[package]
name = "shadow-cli"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
exclude.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
shadow-tracing.workspace = true
shadow-config.workspace = true
shadow-etherscan-fetch.workspace = true
shadow-compile.workspace = true
shadow-init.workspace = true
shadow-push.workspace = true
shadow-simulate.workspace = true
shadow-clone.workspace = true
shadow-common.workspace = true

eyre.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
envy.workspace = true

[[bin]]
name = "shadow"
path = "src/main.rs"
